### ISSUE TITLE
Errors when running `gitclick list`

### ISSUE THREAD

**Issue by daniel-liuzzi** [maximilianschmitt/gitclick#4]
I am trying to start using this tool as it seems very useful, but I'm running into some problems.

First I installed gitclick:

```
~> npm i gitclick -g
~\AppData\Roaming\npm\gitclick -> ~\AppData\Roaming\npm\node_modules\gitclick\bin\gitclick
gitclick@0.4.3 ~\AppData\Roaming\npm\node_modules\gitclick
├── is-iojs@1.1.0
├── home-dir@1.0.0
├── thenify-all@1.6.0
├── create-error@0.3.1
├── minimist@1.1.1
├── thenify@3.1.0 (native-or-bluebird@1.2.0)
├── object.assign@2.0.1 (object-keys@1.0.3, define-properties@1.0.1)
├── gitclick-provider-github@0.0.3 (gitclick-util@0.0.1, underscore@1.8.3, bluebird@1.2.4, github@0.1.16)
├── gitclick-provider-bitbucket@0.0.3 (gitclick-util@0.0.1, underscore@1.8.3, bluebird@1.2.4, superagent@0.18.2)
└── inquirer@0.8.2 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.7, readline2@0.1.1, chalk@1.0.0, lodash@3.7.0, rx@2.5.2)
```

I then ran `gitclick list`. It resulted in the following error:

```
~> gitclick list
The file "~\AppData\Roaming\npm\node_modules\gitclick\node_modules\thenify\index.js" requires `Promise`, but neither `bluebird` nor the native `Promise` implementation were found.
Please install `bluebird` yourself.
```

So I followed the error's suggestion and installed bluebird myself:

```
~> npm i bluebird -g
bluebird@2.9.24 ~\AppData\Roaming\npm\node_modules\bluebird
```

Then I tried `gitclick list` again. This time it resulted in a different error:

```
~> gitclick list
Unhandled rejection ReferenceError: Promise is not defined
    at getListAndDefaultAccount (~\AppData\Roaming\npm\node_modules\gitclick\es5\bin\cli.js:157:16)
    at tryCatcher (~\AppData\Roaming\npm\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (~\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (~\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (~\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (~\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:175:16)
    at Async._drainQueues (~\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:185:10)
    at Async.drainQueues (~\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:442:13)

~>
```

Am I missing something?

My environment:

```
~> node --version
v0.10.36

~> npm --version
1.4.28
```

If it matters, I'm running Windows 8.1 Pro 64-bit.

**Comment by maximilianschmitt** [comment]
Thanks for the bug report, @dliuzzi! It seems like this was slipping through the tests but it should be fixed now in version `0.4.4`. Just run `npm i gitclick -g` again to get the latest version. I haven't done any testing on Windows, so I hope you don't run into any more errors. If you do, please report them here and I'll make sure to get everything working. Thanks! :)

**Comment by daniel-liuzzi** [comment]
Hello Maximilian,

I hate to be the bearer of the bad news, but the problem still occurs in `0.4.4`. Same exact symptoms as before; when bluebird is not installed, I get _neither `bluebird` nor the native `Promise` implementation were found_. After installing bluebird, I get _Unhandled rejection ReferenceError: Promise is not defined_ instead, as shown above. Even the stack trace is identical.

Awesome support BTW.

**Comment by maximilianschmitt** [comment]
Sorry about that, Daniel. Some problems just don't show up when doing local tests. I think the issue was an outdated npm-shrinkwrap.json. I just published `0.4.5` and for me it works with 0.10.x now. Fingers crossed that it does for you, too! :) Thanks again for reporting the issues, it really helps! :)

**Comment by daniel-liuzzi** [comment]
No problem. I'm glad to help! OK, I just tried `0.4.5`. It fixed the dependency problem; I no longer need to manually install bluebird (good!) but unfortunately the reference error persists:

```
~> gitclick list
Unhandled rejection ReferenceError: Promise is not defined
    at getListAndDefaultAccount (~\AppData\Roaming\npm\node_modules\gitclick\es5\bin\cli.js:157:16)
    at tryCatcher (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\async.js:175:16)
    at Async._drainQueues (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\async.js:185:10)
    at Async.drainQueues (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:442:13)
```

With the exception that bluebird is now nested inside gitclick, the stack trace looks the same.

**Comment by maximilianschmitt** [comment]
Thanks for checking back in! Weird that I don't get this error. I will try to reproduce and fix when I get home in a few hours. I'll let you know when I have some results!

**Comment by daniel-liuzzi** [comment]
You're much welcome. If you're familiar with [Docker](https://www.docker.com/), I have just put up [an image](https://registry.hub.docker.com/u/danielliuzzi/ubuntu-node/) which is basically a clean install of Ubuntu + Node and NPM. You can get it by running `docker pull danielliuzzi/ubuntu-node`.

If you run this image and do `npm i gitclick -g` / `gitclick list` within it, you will be able to reproduce the same exact error I describe above. This image being Linux-based, I assume this indicates the error is not Windows-specific. Hope this helps.

Thanks again for your support.

**Comment by maximilianschmitt** [comment]
Hi again Daniel. I think I got it working now (really! ;)). I tested it with the docker image you provided and multiple versions of node.js 0.10.x. The latest gitclick version is `0.4.8`. Please let me know if this works. Thanks again for all the effort you are putting in to helping me find the issue! :)

**Comment by daniel-liuzzi** [comment]
Hey Max. Sorry for the delay. I finally got a chance to try `0.4.8` and bingo! It lets me do `gitclick list` without pre-installing extraneous dependencies, and without errors!

Unfortunately there appears to be some errors in the BitBucket provider, but I will create a new issue, as that is unrelated to the original `gitclick list` problem, which now works perfectly.

Again, thanks a bunch for taking the time and effort to iron things out in such a timely manner.
